version: '2'
services:
  base_node:
    image: node:latest
    volumes:
        # Provide the container with read-write authority over the current directory by default
        # $PWD is considered as active designation
        - $PWD:/usr/node_app
    working_dir: /usr/node_app

  node:
    extends: base_node
    network_mode: none # No connection to the network by default
    
  npm:
    extends: base_node
    volumes:
        # directory for npm -g
        # `npm config get prefix` is /usr/local, but cannot alias that because both npm and node
        # are there, so inventing a new directory
        - $HOME/Logiciel/docker-global-npm:/usr/local/global-npm-modules

  loggednpm:
    extends: base_node
    volumes:
        # for credentials
        - $HOME/.npmrc:/root/.npmrc
  
  # To be started as a daemon 
  # docker-compose -f contained-services.yml run -d dind
  dind:
    image: docker:1.10.3-dind
    privileged: true
    # the container_name does not work with docker-compose run https://github.com/docker/compose/issues/2061
    # Must be passed as command-line argument
    # container_name: test-dind
    volumes:
        # shared as :rw here and to be passed as :ro to inner container
        - $PWD/victim.txt:/home/victim.txt 
        # no mapping initially to an host directory initially, but it will be added dynamically
        - /home/node-app
    
    
    
    
    
    
    