version: '3'
services:
  contained_npm_script:
    build: .
    working_dir: "${GUEST_CWD}"
    # Passing the current user id as user id in the container
    user: "${USER_ID}"
    volumes:
        # Current directory as working_dir
        - "${INIT_CWD}:/home/node-app:ro"
        - "${HOST_CWD}:${GUEST_CWD}" # allowing the package to writing in its own directory

        # Passing node binary
        - /usr/bin/node:/usr/bin/node:ro